### ISSUE TITLE
Multiple Heuristic sensitivity configs

### ISSUE THREAD

**Issue by geNAZt** [Photon-GitHub/AACAdditionPro#11]
AAC has support for additional Data in heuristics. If you catch the PlayerViolationEvent from AAC you could implement multiple Commands for different sensitivity settings:

For example:
```
# Be sure that the lowest level here must be the current AAC heuristic sensitivity setting. 
# Having AAC heuristics sensitivity at 2 will never trigger a sensitivity 1 vl
heuristics:
  # This check does split heuristics into multiple sensitivity levels
  enabled: true
  
  # Commands for multiple sensitivity
  sensitivities:
    1:
      - "aacmessage {player} Did fail sensitivity 1 heuristics"
    2:
      - "aacmessage {player} Did fail sensitivity 2 heuristics"
```

If you have further questions on how to implement ask me on discord :)
