### ISSUE TITLE
ESP doesn't work

### ISSUE THREAD

**Issue by Kylepoops** [Photon-GitHub/AACAdditionPro#424]
### Config of ESP
```
Esp:
  enabled: true
  sleep_millis: 250
  calculate_third_person_modes: false
  low_vector_hitboxes: true
  ray_tracing: true
```
### Plugins List
Plugins (30): AAC5 (5.0.11), AACAdditionPro (6.5.3), Chair (1.4), ChatEx (2.6.1), CommandConfirmation (1.4.0), CoreProtect (19.4), DeathChestPro (3.4.25), floodgate-bukkit (1.0-SNAPSHOT), Geyser-Spigot (1.2.0-SNAPSHOT), Harbor (1.6.3), ImageOnMap (4.0), InventoryRollback (1.4.0), JukeBox (1.20.3), LagAssist (2.23.3), LuckPerms (5.2.94), MoreCommands (19.3), Multiverse-Core (4.2.2-b812), NoteBlockAPI (1.6.1-SNAPSHOT), OpenInv (4.1.5), PlugMan (2.1.7), ProtocolLib (4.6.0-SNAPSHOT-b494), QuantumAPI (1.4.3), QuantumSpawn (1.4.3), Realistic_World (4.25.9), TPAPro (1.2), Triton (3.2.2), Vault (1.7.3-b1
31), VillagerOptimiser (1.1.5), Whitelist (1.0-SNAPSHOT), WorldEdit (7.2.2+fc3c499)
